axis_linear:
  x: 1
  y: 0
scale_linear:
  x: 0.4
  y: 0.4
scale_linear_turbo:
  x: 0.8
  y: 0.8
axis_angular:
  yaw: 2
scale_angular:
  yaw: 0.5
scale_angular_turbo:
  yaw: 1.0
enable_button: 5
enable_turbo_button: 4
